name: CI macOS-latest

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build on macOS
      run: |
        brew install gpatch gmp z3 pkg-config
        brew install opam
        etc/ci_opam_build.sh
